### ISSUE TITLE
How to stop this timer ?

### ISSUE THREAD

**Issue by ChristopheCVB** [XenoPyax/EDJ#3]
https://github.com/XenoPyax/EDJ/blob/d2a0d770c89401cf15396f8479add9585c5d1591/src/org/xenodev/edj/EDJApiBuilder.java#L187

And why not simply continually read the lines of the files instead of waiting for 5s between each read ?

**Comment by XenoPyax** [comment]
This has been addressed in the latest commit [https://github.com/XenoPyax/EDJ/commit/9fdbbd448414d04f16a758fadcfe091745376938](url) removing the Timer and replacing it with a while loop.
