### ISSUE TITLE
Use instanceof

### ISSUE THREAD

**Issue by ChristopheCVB** [XenoPyax/EDJ#4]
https://github.com/XenoPyax/EDJ/blob/d2a0d770c89401cf15396f8479add9585c5d1591/src/org/xenodev/edj/EDJApiBuilder.java#L239

`!(l instanceof EventListener)`

**Comment by XenoPyax** [comment]
This has been addressed in the latest commit [https://github.com/XenoPyax/EDJ/commit/9fdbbd448414d04f16a758fadcfe091745376938](url).

Thank you for pointing it out.
